### ISSUE TITLE
Module doesn't show on user side

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wfdownloads#16]
When I click on the module link (http://mywebsite/modules/wfdownloads/), page return me to the home page.
No error on debug mode.

When I go directly to the file to download, page is displayed:
http://mywebsite/modules/wfdownloads/singlefile.php?cid=1&lid=1
___

My config:

PHP: 5.6.11-1ubuntu3.4
MYSQL: 5.6.30
XOOPS: 2.5.7.2 english version
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
I've done some updates, and I don't have any problems on the user side (PHP 5.6.23 and XOOPS 2.5.8)
But it's still work in progress, so there might be some other issues. 
Please test and let me know if it got better for you....
https://github.com/mambax7/wfdownloads

**Comment by cesagonchu** [comment]
Thx, I'll do some tests tomorrow ;-)

**Comment by cesagonchu** [comment]
Bug still exists.

**Comment by mambax7** [comment]
Can you try to XOOPS 2.5.8?

**Comment by cesagonchu** [comment]
No error on debug mode. I forgot to tell you I tested with Xoops 2.5.8 and default theme.


My config:

PHP: 5.6.11-1ubuntu3.4
MYSQL: 5.6.30
XOOPS: 2.5.8 english version
ModuleAdmin: 1.2

**Comment by mambax7** [comment]
But can you check your PHP "error.log"?

**Comment by cesagonchu** [comment]
Yes, I will take a look.

**Comment by cesagonchu** [comment]
I've downloaded the module from:
http://github.com/XoopsModules25x/wfdownloads

not 

http://github.com/mambax7/wfdownloads

Are they the same?

**Comment by mambax7** [comment]
Most of the time they are - that's why I gave you the link in my original response to my repository:
https://github.com/mambax7/wfdownloads

But if you downloaded it in the last 5 days, then it should be pretty much the same. 

When you're not sure if the fork is the same as the original, you can take a look at "network view": in the repository click on the number box next to the "Fork" button:
![image](https://cloud.githubusercontent.com/assets/613686/16544759/d03d8294-40df-11e6-911e-1d7baea4537d.png)

and it will show you the current status of all the forks, and then you can check out the differences:

![image](https://cloud.githubusercontent.com/assets/613686/16544782/77106abe-40e0-11e6-9c84-cdf8af25a870.png)

**Comment by cesagonchu** [comment]
I downloaded today the module, but I will try with https://github.com/mambax7/wfdownloads

**Comment by cesagonchu** [comment]
I only get this message on log:
"script '/var/www/html/viewtopic.php' not found or unable to stat"

**Comment by cesagonchu** [comment]
Updating our email exchanges:

1) I also get the problem with Xoops 2.5.8 latest version from:
https://github.com/XOOPS/XoopsCore25

and

wfdownloads from:
https://github.com/mambax7/wfdownloads


2) When I want to upload a .zip file here:
/wfdownloads/admin/downloads.php

I get this error:
Fatal error: Call to undefined function wfdownloads_uploading() in /modules/wfdownloads/admin/downloads.php on line 275

**Comment by mambax7** [comment]
OK, it seems like this has been solved...
